# ================================
# Configuración general
# ================================
spring.application.name=hospital-backend
server.port=8081

# ================================
# Base de datos PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5433/hospitaldb
spring.datasource.username=hospital_user
spring.datasource.password=hospital_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================================
# Swagger / OpenAPI
# ================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


